# Generated by Django 4.0.3 on 2022-03-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='slider')),
                ('texto1', models.CharField(max_length=100)),
                ('texto2', models.CharField(max_length=100)),
            ],
        ),
    ]
