# Generated by Django 4.0.3 on 2022-03-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_alter_sliderprincipal_texto1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueHacemos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
    ]
