# Generated by Django 4.0.3 on 2022-03-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_quehacemos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderprincipal',
            options={'verbose_name_plural': 'Slider Principal'},
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sliderprincipal',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
