# Generated by Django 4.0.3 on 2022-03-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_alter_sliderprincipal_options_quehacemos_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quehacemos',
            options={'verbose_name_plural': 'Lo que hacemos'},
        ),
    ]
