# Generated by Django 4.0.3 on 2022-03-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_alter_quehacemos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('linkeding', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Redes Sociales',
            },
        ),
        migrations.AlterModelOptions(
            name='quehacemos',
            options={'verbose_name_plural': '2. Lo que hacemos'},
        ),
        migrations.AlterModelOptions(
            name='sliderprincipal',
            options={'verbose_name_plural': '1. Slider Principal'},
        ),
    ]
