# Generated by Django 4.0.3 on 2022-03-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_redessociales_alter_quehacemos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redessociales',
            old_name='linkeding',
            new_name='linkedin',
        ),
    ]
