# Generated by Django 4.0.3 on 2022-03-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_rename_linkeding_redessociales_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuestrosServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '4. NuestrosServicios',
            },
        ),
    ]
