# Generated by Django 4.0.3 on 2022-03-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_nuestrosservicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nuestrosservicios',
            options={'verbose_name_plural': '4. Nuestros Servicios'},
        ),
        migrations.AddField(
            model_name='nuestrosservicios',
            name='nombre_servicio',
            field=models.CharField(blank=True, help_text='>Texto de no mas de 50 caracteres', max_length=50, null=True),
        ),
    ]
