# Generated by Django 4.0.3 on 2022-03-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0010_nuestrosservicios_breve_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='politicas')),
                ('titulo', models.TextField(help_text='No mas de 50 caracteres', max_length=50)),
                ('breve_descripcion', models.TextField(help_text='No mas de 250 caracteres', max_length=250)),
            ],
        ),
    ]
