# Generated by Django 4.0.3 on 2022-03-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0011_politicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicas',
            options={'verbose_name_plural': '5. Políticas'},
        ),
        migrations.AlterField(
            model_name='politicas',
            name='breve_descripcion',
            field=models.CharField(help_text='No mas de 250 caracteres', max_length=250),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='titulo',
            field=models.CharField(help_text='No mas de 50 caracteres', max_length=50),
        ),
    ]
