# Generated by Django 4.0.3 on 2022-03-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0012_alter_politicas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='No mas de 50 caracteres', max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': '5. Descripción',
            },
        ),
    ]
